# Generated by Django 5.2 on 2025-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_first_init_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
