# Generated by Django 5.2 on 2025-04-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordUpdate",
        ),
    ]
