# Generated by Django 5.2 on 2025-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="app_pass",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
