# Generated by Django 5.2 on 2025-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0002_delete_passwordupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("Social Media", "Social Media"),
                    ("Email", "Email"),
                    ("Personal", "Personal"),
                    ("Work", "Work"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=255,
            ),
        ),
    ]
