# Generated by Django 5.2 on 2025-04-18 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0003_password_created_at_password_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="app_pass",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="password",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passwords",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
